name: Horusec Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  horusec:
    name: horusec
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
          
      - name: Running Horusec
        #we need to ignore sample, automatedTests, automated-tests and .gradle because they are not being shipped the Beagle sdk
        #The two hash was added because we have False Positive on TextInput.swift, we have an enum called PASSWORD, and UrlBuilderDefault.kt, we have a base64 failure but we don't use the base64 on this code
        env:
          HORUSEC_CLI_REPOSITORY_AUTHORIZATION: ${{ secrets.HORUSEC_CLI_REPOSITORY_AUTHORIZATION }}
        run: |
          curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
          horusec start -p . -e true -u "https://api-horusec.zup.com.br" -G true -n "${GITHUB_REPOSITORY}_${GITHUB_REF##*/}"

