name: Pull Request

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    pr_verification:
        name: PR Check
        runs-on: macos-latest

        steps:
            -   name: Checkout repo
                uses: actions/checkout@v2
                with:
                    fetch-depth: 10 # increase this number when in a PR with many commits

            # Gems for Fastlane
            -   name: Cache ruby gems dependencies
                uses: actions/cache@v2
                env:
                    keyPath: ${{ runner.os }}-gems
                with:
                    path: ~/.gem
                    key: ${{ env.keyPath }}-${{ hashFiles('Gemfile.lock') }}
                    restore-keys: ${{ env.keyPath }}
            -   name: Install gem dependencies
                run: bundle config set path '~/.gem' && bundle install

            # SPM
            -   name: Cache SPM dependencies
                uses: actions/cache@v2
                with:
                    path: ~/**/DerivedData/**/SourcePackages
                    key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
                    restore-keys: ${{ runner.os }}-spm

            # Run
            -   name: Run PR Verification
                run: bundle exec fastlane ios pull_request_verification
